#!/usr/bin/env node
// leancraft sync — regenerates agent/context.md + agent/status.md + ledger
// Run: node scripts/leancraft-sync.mjs

import fs from "fs";
import path from "path";
import { execSync } from "child_process";

const root = process.cwd();
const lcRoot = path.join(root, ".leancraft");

function read(p) { try { return fs.readFileSync(p, "utf8"); } catch { return ""; } }
function nowISO() { return new Date().toISOString(); }
function gitCommit() {
  try { return execSync("git rev-parse --short HEAD", { encoding: "utf8" }).trim(); } catch { return "no-git"; }
}

const commit = gitCommit();
const intent = read(path.join(lcRoot, "human/definition/intent.md")).slice(0, 200).replace(/\n/g, " ");
const system = read(path.join(lcRoot, "human/definition/system.md")).slice(0, 200).replace(/\n/g, " ");

// Update agent/context.md
const contextPath = path.join(lcRoot, "agent/context.md");
let context = `# Agent Context — Compressed Repo Memory (AUTO)

> AUTO-GENERATED by \`leancraft sync\` at ${nowISO()}. Commit ${commit}. Human READ-ONLY. Max 500 lines. Agent MUST read this + human/definition/intent.md first.

## Repo Map (auto-scanned)

- Human intent: ${intent || "(empty — fill human/definition/intent.md)"}
- System: ${system || "(empty)"}
- Key dirs: ${fs.existsSync(path.join(root, "src")) ? "src/" : ""} ${fs.existsSync(path.join(root, "app")) ? "app/" : ""} ${fs.existsSync(path.join(root, "lib")) ? "lib/" : ""}

## Last Sync

- Commit: ${commit}
- Time: ${nowISO()}
- Config locked: ${JSON.parse(read(path.join(lcRoot, "config.json")) || '{"locked":false}').locked}

## Open Invariants (from intent.md)

${read(path.join(lcRoot, "human/definition/intent.md")).match(/\*\*I\d+:.*/g)?.join("\n") || "- (none yet — fill intent.md)"}

## Recent Decisions (from joint/decisions.log.md)

${read(path.join(lcRoot, "joint/decisions.log.md")).split("\n").slice(-10).join("\n")}

---
*Overwritten by \`npm run leancraft:sync\`. Do not hand-edit. Max 500 lines.*
`;
fs.writeFileSync(contextPath, context);
console.log(`✓ agent/context.md updated (${commit})`);

// Update agent/status.md
const statusPath = path.join(lcRoot, "agent/status.md");
const validateExists = fs.existsSync(path.join(root, "scripts/leancraft-validate.mjs"));
let validateStatus = "not run — run npm run leancraft:validate";
try {
  execSync("node scripts/leancraft-validate.mjs", { stdio: "pipe" });
  validateStatus = "PASS";
} catch (e) {
  validateStatus = "FAIL — fix errors before Lock";
}

let status = `# Agent Status — Live Tracker (AUTO)

> AUTO-GENERATED at ${nowISO()}, commit ${commit}. Human READ-ONLY.

## Last Sync

- Time: ${nowISO()}
- Commit: ${commit}
- Validate: ${validateStatus}

## Done

- (auto — fill after features ship)

## Todo

- [ ] Fill human/discovery/* (see validate errors above)
- [ ] Distill human/definition/intent.md
- [ ] Run \`npm run leancraft:validate\` → PASS → ask to Lock

## Blocked

- ${validateStatus === "PASS" ? "none" : "validate FAIL — see errors"}

## Budget per run

- Used: 0 / $5.00 (tracked in joint/ledger.jsonl)
- Calls: 0 / 25

---
*Overwritten by sync. Human never edits.*
`;
fs.writeFileSync(statusPath, status);
console.log(`✓ agent/status.md updated`);

// Append ledger
const ledgerPath = path.join(lcRoot, "joint/ledger.jsonl");
const entry = JSON.stringify({ ts: nowISO(), commit, event: "sync", validate: validateStatus }) + "\n";
fs.appendFileSync(ledgerPath, entry);
console.log(`✓ joint/ledger.jsonl appended`);
console.log(`\nSync done.`);
